Feat-implementa-tabelas-cid
ImpulsoGov/SaudeMental pull request #41
Opened 2023-08-01 21:29 UTC by jvns2010

Esse PR é um teste. Estou com problemas pra acessar a área logada localmente. Vou testar as mudanças através do pré deploy da Vercel.

2023-08-02 17:31 UTC, tainnaps requested changes

2023-08-02 17:31 UTC, tainnaps commented on pages/caps/taxadeabandono/index.js
> +                    colunaQuantidade: "Abandonaram no mês",
Pode aceitar essa sugestão de mudança, por favor? Sei que está como abandono no pdf que te passei, mas o nome da página mudou de Taxa de abandono para Taxa de não adesão, com isso algumas palavras usadas no novo painel mudaram

```suggestion
                    colunaQuantidade: "Evadiram no mês",
```

2023-08-02 17:31 UTC, tainnaps commented on pages/caps/taxadeabandono/index.js
> +                    false
```suggestion

```

2023-08-02 17:31 UTC, tainnaps commented on pages/caps/taxadeabandono/index.js
> +      </div>
```suggestion

```

2023-08-02 17:31 UTC, tainnaps commented on pages/caps/taxadeabandono/index.js
> +import { TabelaCid, TabelaDetalhamentoPorCaps } from "../../../components/Tabelas";
```suggestion
import { TabelaCid } from "../../../components/Tabelas";
```

2023-08-02 17:31 UTC, tainnaps commented on pages/caps/novosusuarios/index.js
> +                    false
```suggestion

```

2023-08-02 17:31 UTC, tainnaps commented on pages/caps/novosusuarios/index.js
> +      </div>
```suggestion

```

2023-08-02 17:31 UTC, tainnaps commented on pages/caps/novosusuarios/index.js
> +import { TabelaCid, TabelaDetalhamentoPorCaps } from "../../../components/Tabelas";
A tabela de Detalhamento por caps só é usada na página de Perfil do usuário. Pode remover a importação dela aqui, por favor?

```suggestion
import { TabelaCid } from "../../../components/Tabelas";
```

2023-08-02 17:31 UTC, tainnaps commented on pages/caps/atendimentoindividuais/index.js
> +                    false
A página de **Perfil do usuário** e alguns gráficos na página de **Produção** possuem seleção única de competência, mas nas páginas de **Novos usuários**, **Atendimentos individuais** e **Taxa de não adesão**, a seleção dos filtros de competência é múltipla intencionalmente. Você pode corrigir para que os filtros de competência dessas páginas voltem a permitir seleção múltipla, por favor?

```suggestion

```

2023-08-02 17:31 UTC, tainnaps commented on pages/caps/atendimentoindividuais/index.js
> +      </div>
Oi João! 
A mensagem que você adicionou aqui é referente apenas à tabela de **Detalhamento por estabelecimento**, que exibe os nomes dos estabelecimentos do município e seus dados gerais na página de **Perfil do usuário**. Lá, os estabelecimentos com registro zerado na competência selecionada não são exibidos na tabela.

Já na tabela de CIDs, não são exibidos nomes dos estabelecimentos e sim das condições de saúde do estabelecimento. Além disso, para o caso em que todos os CIDs da competência selecionada pra tabela são zerados, é exibida uma linha com a cor cinza e a legenda `Sem usuários nessa competência`. Logo, não há necessidade dessa mensagem para a tabela de CID. Você pode remover ela dessa e das outras páginas , por favor? 

```suggestion

```

2023-08-02 17:46 UTC, jvns2010 commented on pages/caps/atendimentoindividuais/index.js
> +                    colunaQuantidade: "Realizaram só atv. individual no mês",
Esse aqui tava assim no PDF também, tudo bem?

2023-08-04 17:52 UTC, tainnaps approved these changes

2023-08-04 17:56 UTC, merged